# Generated by Django 6.0.6 on 2026-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField(verbose_name=models.DecimalField(decimal_places=2))),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
