# Generated by Django 6.0.6 on 2026-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='eletronico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='esporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='vestuario',
            field=models.BooleanField(default=False),
        ),
    ]
