# Generated by Django 6.0.6 on 2026-06-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_eletronico_produto_esporte_produto_vestuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='eletronico',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='esporte',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='vestuario',
        ),
    ]
